version: '3'

services:
   db:
     image: mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: webanno
       MYSQL_USER: webanno
       MYSQL_PASSWORD: webanno

   webanno:
     links:
       - db
     depends_on:
       - db
     image: webanno
     ports:
       - 18080:18080
     restart: always
     environment:
       SQLHOST: db
       USER: webanno
       PASSWORD: webanno
volumes:
    db_data:
